name: Validação de testes do salesforce

on:
  pull_request:
    types: [open, reopen]
    branches:
      - 'develop'
      - 'qa'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2-

    - name: Setup Salesforce CLI
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install @salesforce/cli --global
        echo 'export PATH=/usr/local/bin/sfdx:$PATH' >> $GITHUB_ENV
        sfdx update

    - name: Autenticação do Salesforce
      env: 
        SFDX_USERNAME: ${{ secrets.SFDX_USERNAME_DEV }}
        SFDX_PASSWORD: ${{ secrets.SFDX_PASSWORD }}
        SFDX_SECURITY_TOKEN: ${{ secrets.SFDX_SECURITY_TOKEN_DEV }}
      run: |
        echo $SFDX_PASSWORD$SFDX_SECURITY_TOKEN | sfdx force:auth:password:store -u $SFDX_USERNAME

    - name: Validação da cobertura de código
      run: |
        sudo apt-get install jq
        pass_rate=$(sfdx force:apex:test:run --resultformat json --wait 10 --testlevel RunLocalTests --codecoverage -u prod | jq '.[0].passRate') 
        echo "Taxa de aprovação: $pass_rate%"
        
        if [ "$pass_rate" -gt 75 ]; then
          echo "Cobertura de código ok: $pass_rate%"
        else 
          echo "Cobertura de código insuficiente: $pass_rate%"
          exit 1 
        fi

    - name: Deploy em QA
      run: |
        echo"..."
