name: Testes do salesforce (DEV para QA)

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'qa'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Salesforce CLI #INSTALA O SALESFORCE CLI E O ADICIONA NO PATH
      run: |
        npm install --global sfdx-cli
        sfdx update
        sudo apt-get install -y jq
        sudo apt-get install jq
        sudo apt upgrade

    - name: Autenticação do Salesforce
      env: # DEFINE AS VARIAVEIS DE AMBIENTE DO PLAYGROUND
        CONSUMER_KEY_DEV: ${{ secrets.CONSUMER_KEY_DEV }}
        CONSUMER_SECRET_DEV: ${{ secrets.CONSUMER_SECRET_DEV }}
        #SFDX_SECURITY_TOKEN: ${{ secrets.SFDX_SECURITY_TOKEN_DEV }}
      run: |
        curl -o private-key.pem  https://raw.githubusercontent.com/Gus1331/salesforce-pipeline-implementation/refs/heads/main/build/private-key.pem?token=GHSAT0AAAAAACVE5ZGGBEITWWHNF6KPYWQIZX6XLSA
        sfdx force:auth:jwt:grant --clientid #COSTUMER_SECRET_DEV --jwtkeyfile ./private-key.pem --setalias prod --instanceurl https://curious-otter-r1g72t-dev-ed.trailblaze.my.salesforce.com/
        sfdx force:org:list
    
        #sf org login --client-id $CONSUMER_KEY_DEV --client-secret $CONSUMER_SECRET_DEV --instance-url https://curious-otter-r1g72t-dev-ed.trailblaze.my.salesforce.com/
        sfdx force:org:list
        
        # sfdx org login device --instance-url https://curious-otter-r1g72t-dev-ed.trailblaze.my.salesforce.com/
    - name: Validação da cobertura de código
      run: |
        pass_rate=$(sfdx force:apex:test:run --resultformat json --wait 10 --testlevel RunLocalTests --codecoverage -u prod | jq '[.result.summary.passRate]')
        if [ "$pass_rate" -gt 75 ]; then
          echo "Cobertura de código ok: $pass_rate%"
        else 
          echo "Cobertura de código insuficiente: $pass_rate%"
          exit 1
        fi

    - name: Deploy pra QA
      run: |
        echo "Realizando Deploy para ambiente de homologação..."
